	
/*
Copyright (c) 2001, 2015 Alpha Software Corporation
All Rights Reserved.

This JavaScript library is licensed exclusively for use with Alpha Anywhere, Alpha Five,
Alpha Five Application Server, Alpha Anywhere Application Server,
Alpha Five Run Engine, and Alpha Anywhere Run Engine. It is specifically
not licensed for use on a server that does not have installed on it a
licensed copy of the Alpha Five Application Server or the Alpha Anywhere Application Server.
*/



function $(){if(arguments.length==1){var ele=arguments[0];if(typeof ele=='string'){if(document.getElementById(ele))ele=document.getElementById(ele);else if(document.getElementsByName(ele).length>0)ele=document.getElementsByName(ele);else ele=false;}
return ele;}else{var objArr=new Array();var ele=new Object();for(var i=0;i<arguments.length;i++){if(typeof ele=='string'){if(document.getElementById(arguments[i]))ele=document.getElementById(arguments[i]);else if(document.getElementsByName(arguments[i]).length>0)ele=document.getElementsByName(arguments[i]);else ele=false;}
objArr[i]=ele;}
return objArr;}}
function $n(){if(arguments.length==1){var ele=arguments[0];if(typeof ele=='string'){if(document.getElementsByName(ele).length>0)ele=document.getElementsByName(ele);else if(document.getElementById(ele))ele=[document.getElementById(ele)];else ele=[];}
return ele;}else{var objArr=new Array();for(var i=0;i<arguments.length;i++){var ele=arguments[i];if(document.getElementsByName(ele).length>0)ele=document.getElementsByName(ele);else if(document.getElementById(ele))ele=[document.getElementById(ele)];else ele=[];objArr[i]=ele;}
return objArr;}}
function $isChild(ele,pEle){ele=$(ele);pEle=$(pEle);while(ele.tagName.toLowerCase()!='body'){if(ele==pEle)return true;ele=ele.parentNode;}
return false;}
function $cetp(eles,pEle){if(eles.tagName){if($isChild(eles,pEle))return eles;else return false;}else{var eles2=new Array();for(var i=0;i<eles.length;i++){if($isChild(eles[i],pEle)){eles2.push(eles[i]);}}
if(eles2.length>0)return eles2;else return false;}}
function $ae(obj,type,fn){if(obj.attachEvent){obj['e'+type+fn]=fn;obj[type+fn]=function(){obj['e'+type+fn](window.event);}
obj.attachEvent('on'+type,obj[type+fn]);}else
obj.addEventListener(type,fn,false);}
function $re(obj,type,fn){if(obj.detachEvent){obj.detachEvent('on'+type,obj[type+fn]);obj[type+fn]=null;}else
obj.removeEventListener(type,fn,false);}
function $ga(obj,att){if(typeof obj=='string')obj=$n(obj);var pEle=typeof arguments[2]!='undefined'?arguments[2]:false;if(pEle=='')pEle=false;if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
if(obj==false)return false;if(!obj.tagName){var attArr=new Array();for(var i=0;i<obj.length;i++){if(typeof obj[i]!='object')obj[i]=$(obj[i]);if(typeof att=='object'){for(var j=0;j<att.length;i++)
attArr[attArr.length]=obj[i].getAttribute(att[j]);}else{attArr[attArr.length]=obj[i].getAttribute(att);}}
return attArr;}else{if(typeof att=='object'){var attArr=new Array();for(var i=0;i<att.length;i++)
attArr[i]=obj.getAttribute(att[i]);return attArr;}else{return obj.getAttribute(att);}}}
function $sa(obj,att,val){if(typeof obj=='string')obj=$n(obj);var pEle=typeof arguments[3]!='undefined'?arguments[3]:false;if(pEle=='')pEle=false;if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
if(obj==false)return false;if(!obj.tagName){for(var i=0;i<obj.length;i++){if(typeof obj[i]!='object')obj[i]=$(obj[i]);if(typeof att=='object'){for(var j=0;j<att.length;i++)
obj[i].setAttribute(att[j],val[j]);}else{obj[i].setAttribute(att,val);}}}else{if(typeof att=='object'){for(var i=0;i<att.length;i++)
obj.setAttribute(att[i],val[i]);}else{obj.setAttribute(att,val);}}}
function $gv(obj){var pEle=typeof arguments[1]!='undefined'?arguments[1]:false;if(obj.constructor==Array){var objArr=new Array();var tag='';for(var i=0;i<obj.length;i++){objArr[i]=$gvs(obj[i],pEle);}
return objArr;}else{return $gvs(obj,pEle);}}
function $gvs(obj){var pEle=typeof arguments[1]!='undefined'?arguments[1]:false;if(pEle=='')pEle=false;var honorHTML=typeof arguments[2]!='undefined'?arguments[2]:true;if(typeof obj=='string')obj=$n(obj);if(obj.tagName)obj=[obj];if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
var tag='';var type='';var tArr=new Array();var notArray=false;for(var i=0;i<obj.length;i++){tag=obj[i].tagName.toLowerCase();if(tag=='input')type=obj[i].type.toLowerCase();else type='';if(type=='checkbox'||type=='radio'){if(obj[i].checked==true)tArr.push(obj[i].value);if((type=='checkbox'&&obj.length==1)||type=='radio')notArray=true;}else if(tag=='input'||tag=='textarea'){tArr.push(obj[i].value);notArray=true;}else if(tag=='select'){if(obj[i].multiple==true){for(var j=0;j<obj[i].options.length;j++){if(obj[i].options[j].selected==true)
tArr.push(obj[i].options[j].value);}}else{tArr.push(obj[i].value);notArray=true;}}else if(tag=='img'){tArr.push(obj[i].src);}else{if(honorHTML)tArr.push(obj[i].innerHTML);else if(obj[i].textContent)tArr.push(obj[i].textContent);else if(obj[i].innerText)tArr.push(obj[i].innerText);else tArr.push(obj[i].innerHTML);notArray=true;}}
if(notArray){if(tArr.length==0)return'';else return tArr[0];}else return tArr;}
function $sv(obj,val){var pEle=typeof arguments[2]!='undefined'?arguments[2]:false;if(obj.constructor==Array){if(typeof val=='object'){for(var i=0;i<obj.length;i++){$svs(obj[i],val[i],pEle);}}else{for(var i=0;i<obj.length;i++){$svs(obj[i],val,pEle);}}}else{$svs(obj,val,pEle);}}
function $svs(obj,val){if(val==null)val='';var pEle=typeof arguments[2]!='undefined'?arguments[2]:false;if(pEle=='')pEle=false;var honorHTML=typeof arguments[3]!='undefined'?arguments[3]:true;if(typeof obj=='string')obj=$n(obj);if(obj.tagName)obj=[obj];if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
var tag='';var type='';var ele=new Object();for(var i=0;i<obj.length;i++){ele=obj[i];tag=ele.tagName.toLowerCase();if(tag=='input')type=ele.type.toLowerCase();else type='';if(type=='checkbox'||type=='radio'){if(val.constructor==Array){if($u.a.find(val,ele.value)!=-1)ele.checked=true;else ele.checked=false;}else if(typeof val=='boolean'){ele.checked=val;}else{if(ele.value==val)ele.checked=true;else ele.checked=false;}}else if(tag=='select'){if(val.constructor==Array){for(var j=0;j<ele.options.length;j++){if($u.a.find(val,ele.options[j].value)!=-1)ele.options[j].selected=true;else ele.options[j].selected=false;}}else{ele.value=val;}}else if(tag=='input'||tag=='textarea'){if(val.constructor==Array)ele.value=val.join('\n');else ele.value=val;}else if(tag=='img'){if(val.constructor==Array){if(typeof val[0]!='undefined')ele.src=val[0];if(typeof val[1]!='undefined')ele.title=val[1];}else ele.src=val;}else if(tag=='a'){if(val.constructor==Array){if(typeof val[0]!='undefined'){if(honorHTML)ele.innerHTML=val[0];else ele.innerHTML=val[0].replace(/\n/g,'\n<br/>');}
if(typeof val[1]!='undefined')ele.href=''+val[1];if(typeof val[2]!='undefined')ele.title=val[2];}else{if(honorHTML)ele.innerHTML=val;else ele.innerHTML=val.replace(/\n/g,'\n<br/>');}}else{if(val.constructor==Array)val=val.join('\n');else val=''+val;if(honorHTML)ele.innerHTML=val;else ele.innerHTML=val.replace(/\n/g,'\n<br/>');}}}
function $gvById(obj){if(typeof obj=='object'){var objArr=new Array();for(var i=0;i<obj.length;i++)
objArr[i]=$gv($(obj[i]));return objArr;}else{return $gv($(obj));}}
function $svById(obj,val){if(typeof obj=='object'){for(var i=0;i<obj.length;i++)
$sv($(obj[i]),val[i]);}else{$sv($(obj),val);}}
function $gs(obj){if(typeof obj=='string')obj=$n(obj);var pEle=typeof arguments[1]!='undefined'?arguments[1]:false;if(pEle=='')pEle=false;if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
if(obj==false)return false;if(!obj.tagName){var styleArr=new Array();var tObj=new Object();for(var i=0;i<obj.length;i++){tObj=$(obj[i]);styleArr[styleArr.length]=tObj.style.cssText;}
return styleArr;}else{return obj.style.cssText;}}
function $ss(obj,styleObj){if(typeof obj=='string')obj=$n(obj);var pEle=typeof arguments[2]!='undefined'?arguments[2]:false;if(pEle=='')pEle=false;if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
if(obj==false)return false;if(!obj.tagName){var tObj=new Object();for(var i=0;i<obj.length;i++){tObj=$(obj[i]);if(typeof styleObj=='string')tObj.style.cssText=styleObj;else for(var prop in styleObj)tObj.style[prop]=styleObj[prop];}}else{if(typeof styleObj=='string')obj.style.cssText=styleObj;else for(var prop in styleObj)obj.style[prop]=styleObj[prop];}}
function $scn(obj,val){if(typeof obj=='string')obj=$n(obj);var pEle=typeof arguments[2]!='undefined'?arguments[2]:false;if(pEle=='')pEle=false;if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
if(obj==false)return false;if(!obj.tagName){var tObj=new Object();for(var i=0;i<obj.length;i++){tObj=$(obj[i]);tObj.className=val;}}else obj.className=val;}
function $acn(obj,val){if(typeof obj=='string')obj=$n(obj);var pEle=typeof arguments[2]!='undefined'?arguments[2]:false;if(pEle=='')pEle=false;if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
if(obj==false)return false;if(!obj.tagName){var tObj=new Object();for(var i=0;i<obj.length;i++){tObj=$(obj[i]);if(String(' '+tObj.className+' ').search(' '+val+' ')==-1)tObj.className=$u.s.aTrim(tObj.className+' '+val);}}else if(String(' '+obj.className+' ').search(' '+val+' ')==-1)obj.className=$u.s.lTrim(obj.className+' '+val);}
function $rcn(obj,val){if(typeof obj=='string')obj=$n(obj);var pEle=typeof arguments[2]!='undefined'?arguments[2]:false;if(pEle=='')pEle=false;if(pEle){if(pEle.constructor==Function)obj=pEle(obj);else obj=$cetp(obj,pEle);}
if(obj==false)return false;if(!obj.tagName){var tObj=new Object();for(var i=0;i<obj.length;i++){tObj=$(obj[i]);tObj.className=$u.s.aTrim($u.s.tran(' '+tObj.className+' ',' '+val+' ',' '));}}else obj.className=$u.s.aTrim($u.s.tran(' '+obj.className+' ',' '+val+' ',' '));}
function $cdn(obj){var n;if(typeof obj=='string'){n=document.createTextNode(obj);}else{n=document.createElement(obj.tagName);delete obj.tagName;if(obj.children){if(obj.children.constructor==Array){for(var i=0;i<obj.children.length;i++)n.appendChild($cdn(obj.children[i]));}else{n.appendChild($cdn(obj.children));}
delete obj.children;}
for(var attr in obj){if(attr!='style')n[attr]=obj[attr];else $ss(n,obj[attr]);}}
return n}
function $swto(objId){var obj=$(objId);var y=$gpt(obj);var x=$gpl(obj);window.scrollTo(x,y);}
function $sor(chObj,obj,type){type=type.toLowerCase();var w=obj.offsetWidth;var h=obj.offsetHeight;if(type!='hw'&&type!='h'){var wOff=arguments[3]?arguments[3]:0;var hOff=arguments[4]?arguments[4]:0;}else{var wOff=arguments[4]?arguments[4]:0;var hOff=arguments[3]?arguments[3]:0;}
if(wOff<1&&wOff>0)wOff=Math.round(w*Math.abs(wOff-1));if(hOff<1&&hOff>0)hOff=Math.round(h*Math.abs(hOff-1));if(type=='w')chObj.style.width=(w-wOff)+'px';else if(type=='h')chObj.style.height=(h-hOff)+'px';else if(type=='wh'||type=='hw'){chObj.style.width=(w-wOff)+'px';chObj.style.height=(h-hOff)+'px';}}
function $gpt(obj){var ignoreNonPos=typeof arguments[1]!='undefined'?arguments[1]:false;var tPos=0;if(ignoreNonPos){pEle=obj.parentNode;if(pEle.tagName.toLowerCase()!='html'&&pEle.tagName.toLowerCase()!='body'){while(pEle.tagName.toLowerCase()!='body'){if(pEle.style.position=='absolute'||pEle.style.position=='relative')tPos+=pEle.offsetTop;pEle=pEle.parentNode;}}}else{var b=obj.getBoundingClientRect();var tS=Math.max(document.body.scrollTop,document.documentElement.scrollTop);tPos=b.top+tS;}
return tPos;}
function $gpl(obj){var ignoreNonPos=typeof arguments[1]!='undefined'?arguments[1]:false;var lPos=0;if(ignoreNonPos){pEle=obj.parentNode;if(pEle.tagName.toLowerCase()!='html'&&pEle.tagName.toLowerCase()!='body'){while(pEle.tagName.toLowerCase()!='body'){if(pEle.style.position=='absolute'||pEle.style.position=='relative')lPos+=pEle.offsetLeft;pEle=pEle.parentNode;}}}else{var b=obj.getBoundingClientRect();var lS=Math.max(document.body.scrollLeft,document.documentElement.scrollLeft);lPos=b.left+lS;}
return lPos;}
function $po(chObj,obj,type){var mOff=arguments[3]?arguments[3]:0;var sOff=arguments[4]?arguments[4]:0;var pTop=$gpt(obj);var pLeft=$gpl(obj);var pWidth=obj.offsetWidth;var pHeight=obj.offsetHeight;var cTop=$gpt(chObj.parentNode,true);var cLeft=$gpl(chObj.parentNode,true);var cWidth=chObj.offsetWidth;var cHeight=chObj.offsetHeight;var tEle=chObj.parentNode;while(tEle.tagName.toLowerCase()!='body'){if(tEle.style.position=='absolute'||tEle.style.position=='relative'){cLeft=+$gpl(tEle);cTop=+$gpt(tEle);break;}
tEle=tEle.parentNode;}
if(isNaN(type)){if(typeof type=='string'){type=type.toLowerCase();if(typeof window.innerWidth=='number'){var pageWidth=window.innerWidth;var pageHeight=window.innerHeight;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){var pageWidth=document.documentElement.clientWidth;var pageHeight=document.documentElement.clientHeight;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){var pageWidth=document.body.clientWidth;var pageHeight=document.body.clientHeight;}
if(typeof window.pageYOffset=='number'){pageWidth=pageWidth+window.pageXOffset;pageHeight=pageHeight+window.pageYOffset;}else if(document.documentElement&&typeof document.documentElement.scrollLeft!='undefined'){pageWidth=pageWidth+document.documentElement.scrollLeft;pageHeight=pageHeight+document.documentElement.scrollTop;}else if(document.body&&typeof document.body.scrollLeft!='undefined'){pageWidth=pageWidth+document.body.scrollLeft;pageHeight=pageHeight+document.body.scrollTop;}
if(type=='dropdown'){type=14;if(pTop+pHeight+cHeight>pageHeight&&pTop-cHeight>0)type=2;if((pLeft+sOff)+cWidth>pageWidth)pLeft=(pageWidth-cWidth)-sOff;}else if(type=='dropdown-right'){type=15;if(pTop+pHeight+cHeight>pageHeight&&pTop-cHeight>0)type=3;if((pLeft+(pWidth-cWidth)-sOff)<0)pLeft=(cWidth-pWidth)+sOff;}else if(type=='flyout'){type=8;if(pLeft+pWidth+cWidth>pageWidth&&pLeft-cWidth>0)type=5;if((pTop+sOff)+cHeight>pageHeight)pTop=(pageHeight-cHeight)-sOff;}else if(type=='flyout-bottom'){type=12;if(pLeft+pWidth+cWidth>pageWidth&&pLeft-cWidth>0)type=9;if((pTop-(cHeight-pHeight)-sOff)<0)pTop=(cHeight-pHeight)+sOff;}else if(type=='popup'){type=6;if(pTop+cHeight>pageHeight&&pTop-cHeight>0)type=10;if((pLeft+sOff)+cWidth>pageWidth)pLeft=(pageWidth-cWidth)-sOff;}else if(type=='popup-bottom'){type=10;if((pTop-(cHeight-pHeight)-sOff)<0)pTop=(cHeight-pHeight)+sOff;if((pLeft+sOff)+cWidth>pageWidth)pLeft=(pageWidth-cWidth)-sOff;}}else type=14;}
switch(type){case(1):chObj.style.left=(pLeft-cWidth-mOff-cLeft)+'px';chObj.style.top=(pTop-cHeight-sOff-cTop)+'px';break
case(2):chObj.style.left=(pLeft+sOff-cLeft)+'px';chObj.style.top=(pTop-cHeight-mOff-cTop)+'px';break
case(3):chObj.style.left=(pLeft+(pWidth-cWidth)-sOff-cLeft)+'px';chObj.style.top=(pTop-cHeight-mOff-cTop)+'px';break
case(4):chObj.style.left=(pLeft+pWidth+mOff-cLeft)+'px';chObj.style.top=(pTop-cHeight-sOff-cTop)+'px';break
case(5):chObj.style.left=(pLeft-cWidth-mOff-cLeft)+'px';chObj.style.top=(pTop+sOff-cTop)+'px';break
case(6):chObj.style.left=(pLeft+sOff-cLeft)+'px';chObj.style.top=(pTop+mOff-cTop)+'px';break
case(7):chObj.style.left=(pLeft+pWidth-cWidth-sOff-cLeft)+'px';chObj.style.top=(pTop+mOff-cTop)+'px';break
case(8):chObj.style.left=(pLeft+pWidth+mOff-cLeft)+'px';chObj.style.top=(pTop+sOff-cTop)+'px';break
case(9):chObj.style.left=(pLeft-cWidth-mOff-cLeft)+'px';chObj.style.top=(pTop-(cHeight-pHeight)-sOff-cTop)+'px';break
case(10):chObj.style.left=(pLeft+sOff-cLeft)+'px';chObj.style.top=(pTop-(cHeight-pHeight)-mOff-cTop)+'px';break
case(11):chObj.style.left=(pLeft+pWidth-cWidth-sOff-cLeft)+'px';chObj.style.top=(pTop-(cHeight-pHeight)-mOff-cTop)+'px';break
case(12):chObj.style.left=(pLeft+pWidth+mOff-cLeft)+'px';chObj.style.top=(pTop-(cHeight-pHeight)-sOff-cTop)+'px';break
case(13):chObj.style.left=(pLeft-cWidth-mOff-cLeft)+'px';chObj.style.top=(pTop+pHeight+sOff-cTop)+'px';break
case(14):chObj.style.left=(pLeft+sOff-cLeft)+'px';chObj.style.top=(pTop+pHeight+mOff-cTop)+'px';break
case(15):chObj.style.left=(pLeft+(pWidth-cWidth)-sOff-cLeft)+'px';chObj.style.top=(pTop+pHeight+mOff-cTop)+'px';break
case(16):chObj.style.left=(pLeft+pWidth+mOff-cLeft)+'px';chObj.style.top=(pTop+pHeight+sOff-cTop)+'px';break
case(17):chObj.style.left=(pLeft+Math.round(pWidth/2)-Math.round(cWidth/2)+sOff-cLeft)+'px';chObj.style.top=(pTop-cHeight-mOff-cTop)+'px';break
case(18):chObj.style.left=(pLeft-cWidth-mOff-cLeft)+'px';chObj.style.top=(pTop+Math.round(pHeight/2)-Math.round(cHeight/2)+sOff-cTop)+'px';break
case(19):chObj.style.left=(pLeft+Math.round(pWidth/2)-Math.round(cWidth/2)+sOff-cLeft)+'px';chObj.style.top=(pTop+Math.round(pHeight/2)-Math.round(cHeight/2)+mOff-cTop)+'px';break
case(20):chObj.style.left=(pLeft+pWidth+mOff-cLeft)+'px';chObj.style.top=(pTop+Math.round(pHeight/2)-Math.round(cHeight/2)+sOff-cTop)+'px';break
case(21):chObj.style.left=(pLeft+Math.round(pWidth/2)-Math.round(cWidth/2)+sOff-cLeft)+'px';chObj.style.top=(pTop+pHeight+mOff-cTop)+'px';break}}
var Class={create:function(){var baseKlass=null
var props=new Array();for(var i=0;i<arguments.length;i++)props[i]=arguments[i];if(props[0])if(props[0].constructor==Function)baseKlass=props.shift();klass=function(){this.initialize.apply(this,arguments);}
klass.superclass=baseKlass;if(baseKlass){var tempKlass=function(){};tempKlass.prototype=baseKlass.prototype;klass.prototype=new tempKlass;}
for(var i=0;i<props.length;i++)$u.o.assign(klass.prototype,props[i]);if(!klass.prototype.initialize)klass.prototype.initialize=function(){};klass.prototype.constructor=klass;return klass;},superclassMethod:function(klass,method,args,context){if(klass.constructor.superclass.prototype[method]){if(klass.constructor.superclass.prototype[method].constructor==Function){if(!context)klass.constructor.superclass.prototype[method].apply(klass,args);else klass.constructor.superclass.prototype[method].apply(context,args);}}}}
function $if(expr,tVal,fVal){return expr?tVal:fVal;}
var $u={comma:',',decimal:'.',currency:'$',days:['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],daysShort:['sun','mon','tue','wed','thur','fri','sat'],months:['january','february','march','april','may','june','july','august','september','october','november','december'],monthsShort:['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'],compare:function(obj1,obj2){if(obj1==obj2)
return true;var val1=$u.o.toJSON(obj1);var val2=$u.o.toJSON(obj2);if(val1==val2)
return true;return false;},s:{toNum:function(str){if(typeof str=='number')return str;str=str.toString();if(str.search('\\(')!=-1)str='-'+str;var regEx=RegExp('[^\-0-9'+$u.decimal+']');str=str.split(regEx).join('');if(str.indexOf('-')!=-1){var negNum=(str.indexOf('-')==0)?true:false;var regEx=RegExp('[^0-9'+$u.decimal+']');str=$if(negNum,'-','')+str.split(regEx).join('');}
str=str.replace($u.decimal,'.');return Number(str);},toBool:function(str){str=str.toString();if(str=='')return false;str=$u.s.aTrim(str).toLowerCase();if(str=='true'||str=='t'||str=='yes'||str=='1'||str=='.t.'){return true;}else
return false;},lTrim:function(str,tc){str=str.toString();if(!tc||tc=='')tc=' ';while(tc.indexOf(str.charAt(0))!=-1){str=str.substring(1,str.length);if(str.length==0)return'';}
return str;},substr:function(str,start,sLength){str=str.toString();if(start<0)start=str.length+start;if(typeof sLength=='undefined')return str.substr(start);else return str.substr(start,sLength);},rTrim:function(str,tc){str=str.toString();if(!tc||tc=='')tc=' ';while(tc.indexOf(str.charAt(str.length-1))!=-1){str=str.substring(0,str.length-1);if(str.length==0)return'';}
return str;},aTrim:function(str,tc){str=str.toString();if(!tc||tc=='')tc=' ';str=this.lTrim(str,tc);str=this.rTrim(str,tc);return str;},tran:function(str,sStr,rStr){str=str.toString();if(typeof sStr=='object'){for(var i=0;i<sStr.length;i++){var arr=str.split(sStr[i]);str=arr.join(rStr[i]);}}else{var arr=str.split(sStr);str=arr.join(rStr);}
return str;},word:function(str,num,sep){str=str.toString();if(sep=='')sep=' ';var arr=str.split(sep);if(Math.abs(num)>arr.length)return'';else if(num>-1)return arr[num-1];else return arr[arr.length+num];},ellipse:function(str,len){str=str.toString();var elpStr=(arguments[3])?arguments[3]:'...';var align=(arguments[2])?arguments[2].substring(0,1).toLowerCase():'l';if(align=='r'){str=str.substring(0,len-elpStr.length)+elpStr;}else if(align=='c'){var lLen=Math.round((len-elpStr.length)/2);var rLen=str.length-(len-elpStr.length-lLen);str=str.substring(0,lLen)+elpStr+str.substring(rLen,str.length);}else{str=elpStr+str.substring(str.length-(len-elpStr.length),str.length);}
return str;},pad:function(str,padLen,padStr){str=str.toString();var align=arguments[3]?arguments[3].toLowerCase():'l';if(padLen==-1){return str;}else if(str.length>padLen){return str.substr(0,padLen);}else{padStr=$u.s.replicate(padStr,padLen)
if(align=='l'){return padStr.substring(0,padLen-str.length)+str;}else if(align=='r'){return str+padStr.substring(0,padLen-str.length);}else if(align=='c'){padLen=padLen-str.length;var lLen=Math.round(padLen/2);var rLen=padLen-lLen;return padStr.substring(0,lLen)+str+padStr.substring(0,rLen);}}},replicate:function(str,repNum){str=str.toString();var repArr=new Array();for(var i=0;i<repNum;i++)repArr.push(str);return repArr.join('');},changeCase:function(str,type){str=str.toString();type=type.toLowerCase();switch(type){case('u'):return str.toUpperCase();break
case('l'):return str.toLowerCase();break
case('fu'):return str.substr(0,1).toUpperCase()+str.substr(1);break
case('furl'):return str.substr(0,1).toUpperCase()+str.substr(1).toLowerCase();break
case('wfu'):var wordsArr=str.split(' ');for(var i=0;i<wordsArr.length;i++)wordsArr[i]=$u.s.changeCase(wordsArr[i],'fu');return wordsArr.join(' ');break
case('wfurl'):str=str.toLowerCase();var wordsArr=str.split(' ');for(var i=0;i<wordsArr.length;i++)wordsArr[i]=$u.s.changeCase(wordsArr[i],'fu');return wordsArr.join(' ');break}}},n:{toStr:function(valNum){if(typeof valNum=='string')return valNum;var decNum=arguments[1]?arguments[1]:-1;var format=arguments[2]?arguments[2].toUpperCase():'';if(format.indexOf('B')!=-1&&valNum==0)return'';var comma=(format.indexOf(',')!=-1)?true:false;var prefixNeg=(format.indexOf('-')!=-1)?true:false;var parenNeg=(format.indexOf('(')!=-1)?true:false;var negStr=valNum<0?'-':'';var prefix=arguments[3]?arguments[3]:'';var suffix=arguments[4]?arguments[4]:'';if(decNum!=-1)valNum=$u.n.round(Math.abs(valNum),decNum);else valNum=Math.abs(valNum);var str=String(valNum);var intStr=$u.s.word(str,1,'.');var decStr=$u.s.word(str,2,'.');if(decNum!=-1){if(!decStr)decStr='0';if(decStr.length!=decNum)decStr=$u.s.pad(decStr,decNum,'0','r');}
if(comma&&intStr.length>3){var intArr=new Array();var placeInc=Math.round((intStr.length/3)+.49);intStr=$u.s.pad(intStr,placeInc*3,'0','l')
intArr.push($u.s.lTrim(intStr.substr(0,3),'0'));for(var i=1;i<placeInc;i++){intArr.push(intStr.substr(i*3,3));}
intStr=intArr.join($u.comma);}
if(prefixNeg&&negStr!='')prefix=negStr+prefix;else if(parenNeg&&negStr!=''){prefix='('+prefix;suffix=suffix+')';}else intStr=negStr+intStr;if(decStr!='')return prefix+intStr+$u.decimal+decStr+suffix;else return prefix+intStr+suffix;},toPlaceStr:function(num){num=Math.round(num);var numStr=String(num);var numEnd=parseInt(numStr.slice(-2));if(numEnd>3&&numEnd<21)
return numStr+'th';var numEnd=parseInt(numStr.slice(-1));if(numEnd==1)
return numStr+'st';else if(numEnd==2)
return numStr+'nd';else if(numEnd==3)
return numStr+'rd';else
return numStr+'th';},round:function(valNum,decNum){if(!isNaN(valNum)&&!isNaN(decNum)){var dir=typeof arguments[2]!='undefined'?arguments[2].substr(0,1).toLowerCase():'';var tempDecNum=Math.pow(10,decNum);if(dir=='u')return(Math.round((valNum*tempDecNum)+.49999)/tempDecNum);else if(dir=='d')return(Math.round((valNum*tempDecNum)-.49999)/tempDecNum);else{var offset=0;if(dir=='a')offset=.49999;else if(dir=='t')offset=-.49999;if(valNum>0)return(Math.round((valNum*tempDecNum)+offset)/tempDecNum);else return(Math.round(Math.abs(valNum*tempDecNum)+offset)/tempDecNum)*-1;}}}},a:{find:function(){var arr=arguments[0];var val=arguments[1];var searchAll=typeof arguments[2]!='undefined'?arguments[2]:false;var exactMatch=typeof arguments[3]!='undefined'?arguments[3]:true;var indxArr=Array();if(exactMatch==true){for(var i=0;i<arr.length;i++){if(arr[i]==val){indxArr.push(i);if(searchAll!=true)break;}}}else{for(var i=0;i<arr.length;i++){if(String(arr[i]).indexOf(String(val))!=-1){indxArr.push(i);if(searchAll!=true)break;}}}
if(indxArr.length==0)
indxArr.push(-1);if(searchAll==true){return indxArr;}else{return indxArr[0];}},compare:function(a,b){var type=arguments[2]?arguments[2]:'<';if(typeof a!='object')
a=new Array(a);if(typeof b!='object')
b=new Array(b);var indx=new Array();var tArr=new Array();if(type=='>'){for(var i=0;i<a.length;i++){indx=$u.a.find(b,a[i]);if(indx==-1)
tArr[tArr.length]=a[i];}}else if(type=='='){for(var i=0;i<b.length;i++){indx=$u.a.find(a,b[i]);if(indx!=-1)
Arr[tArr.length]=b[i];}}else{for(var i=0;i<b.length;i++){indx=$u.a.find(a,b[i]);if(indx==-1)
tArr[tArr.length]=b[i];}}
return tArr;},dedup:function(arr){var tArr=new Array();for(var i=0;i<arr.length;i++){if($u.a.find(tArr,arr[i])==-1)
tArr[tArr.length]=arr[i];}
return tArr;},copy:function(arr){return new Array(arr);}},o:{assign:function(objD,obj){var lAssign=typeof arguments[2]!='undefined'?arguments[2]:false
if(lAssign){for(var prop in obj){if(typeof obj[prop]=='object'&&typeof objD[prop]=='object'&&obj[prop]!=null&&obj[prop].constructor!=Date&&obj[prop].constructor!=RegExp){if(!objD[prop]){if(obj[prop].constructor==Array)objD[prop]=[];else objD[prop]={};}
$u.o.assign(objD[prop],obj[prop],lAssign);}else if(typeof objD[prop]=='undefined')objD[prop]=obj[prop];}}else{for(var prop in obj){if(typeof obj[prop]=='object'&&obj[prop]!=null&&obj[prop].constructor!=Date&&obj[prop].constructor!=RegExp){if(!objD[prop]||typeof objD[prop]!='object'){if(obj[prop].constructor==Array)objD[prop]=[];else objD[prop]={};}
$u.o.assign(objD[prop],obj[prop],lAssign);}else objD[prop]=obj[prop];}}},toJSON:function(obj){if(obj==null)return'null';var type=typeof(obj);if(type=='undefined')return'\'\'';if(type=='object'){var propArr=new Array();if(obj.length){for(var i=0;i<obj.length;i++)propArr.push($u.o.toJSON(obj[i]));return'['+propArr.join(', ')+']';}else{for(var prop in obj)propArr.push(prop+': '+$u.o.toJSON(obj[prop]));return'{'+propArr.join(', ')+'}';}}else if(type=='number')return String(obj);else if(type=='boolean')return obj?'true':'false';else if(type=='date')return'Date(\''+obj+'\')';else if(type=='date')return'Date(\''+obj+'\')';else return'\''+$u.s.tran($u.s.tran(obj,'\'','\\\''),'\n','\\n')+'\'';},toParams:function(obj){var prefix=arguments[1]||'';var encode=typeof arguments[2]!='undefined'?arguments[2]:true;if(encode)prefix=prefix.replace(/%/g,"%25").replace(/\+/g,"%2B").replace(/\=/g,"%3D").replace(/\\/g,"%5C").replace(/&/g,"%26").replace(/\n/g,"%0D%0A").replace(/\r/g,"");var type=typeof(obj);if(type=='object'){if(obj==null)return prefix+"=";var propArr=new Array();if(obj.length){var prefixArrIt=$u.s.tran(prefix,'[]','[..]');for(var i=0;i<obj.length;i++){if(i==0){if(typeof obj[i]=='object'){propArr.push($u.o.toParams(obj[i],prefix+'[]',encode));}else{propArr.push(prefix+'[]='+$u.o.toParams(obj[i],'',encode));}}else{if(typeof obj[i]=='object'){propArr.push($u.o.toParams(obj[i],prefixArrIt+'[]',encode));}else{propArr.push(prefixArrIt+'[]='+$u.o.toParams(obj[i],'',encode));}}}
return propArr.join('&');}else{if(prefix!='')prefix=prefix+'.';var prefixArrIt=$u.s.tran(prefix,'[]','[..]');var propCount=0;var propStr='';for(var prop in obj){propStr=prop;if(encode)propStr=propStr.replace(/%/g,"%25").replace(/\+/g,"%2B").replace(/\=/g,"%3D").replace(/\\/g,"%5C").replace(/&/g,"%26").replace(/\n/g,"%0D%0A").replace(/\r/g,"");if(propCount==0){if(typeof obj[prop]=='object'){propArr.push($u.o.toParams(obj[prop],prefix+prop,encode));}else{propArr.push(prefix+propStr+'='+$u.o.toParams(obj[prop],'',encode));}}else{if(typeof obj[prop]=='object'){propArr.push($u.o.toParams(obj[prop],prefixArrIt+prop,encode));}else{propArr.push(prefixArrIt+propStr+'='+$u.o.toParams(obj[prop],'',encode));}}
propCount++}
return propArr.join('&');}}else{if(type=='number')return String(obj);else if(type=='boolean')return obj?'.t.':'.f.';else if(encode)return''+obj.replace(/%/g,"%25").replace(/\+/g,"%2B").replace(/\=/g,"%3D").replace(/\\/g,"%5C").replace(/&/g,"%26").replace(/\n/g,"%0D%0A").replace(/\r/g,"");else return''+obj;}}},d:{toStr:function(dObj,frm){if(frm.indexOf('[mm]')!=-1)
frm=frm.replace('[mm]',$u.s.pad(''+(dObj.getMonth()+1),2,'0'));else if(frm.indexOf('[m]')!=-1)
frm=frm.replace('[m]',''+(dObj.getMonth()+1));else if(frm.indexOf('[month]')!=-1)
frm=frm.replace('[month]',$u.months[dObj.getMonth()]);else if(frm.indexOf('[Month]')!=-1)
frm=frm.replace('[Month]',$u.s.changeCase($u.months[dObj.getMonth()],'fu'));else if(frm.indexOf('[MONTH]')!=-1)
frm=frm.replace('[MONTH]',$u.months[dObj.getMonth()].toUpperCase());else if(frm.indexOf('[mon]')!=-1)
frm=frm.replace('[mon]',$u.monthsShort[dObj.getMonth()]);else if(frm.indexOf('[Mon]')!=-1)
frm=frm.replace('[Mon]',$u.s.changeCase($u.monthsShort[dObj.getMonth()],'fu'));else if(frm.indexOf('[MON]')!=-1)
frm=frm.replace('[MON]',$u.monthsShort[dObj.getMonth()].toUpperCase());if(frm.indexOf('[dd]')!=-1)
frm=frm.replace('[dd]',$u.s.pad(''+(dObj.getDate()),2,'0'));else if(frm.indexOf('[d]')!=-1)
frm=frm.replace('[d]',''+(dObj.getDate()));else if(frm.indexOf('[ddx]')!=-1)
frm=frm.replace('[ddx]',$u.s.pad($u.n.toPlaceStr(dObj.getDate()),2,'0'));else if(frm.indexOf('[dx]')!=-1)
frm=frm.replace('[dx]',$u.n.toPlaceStr(dObj.getDate()));else if(frm.indexOf('[DDX]')!=-1)
frm=frm.replace('[DDX]',$u.s.pad($u.n.toPlaceStr(dObj.getDate()),2,'0').toUpperCase());else if(frm.indexOf('[DX]')!=-1)
frm=frm.replace('[DX]',$u.n.toPlaceStr(dObj.getDate()).toUpperCase());if(frm.indexOf('[yy]')!=-1)
frm=frm.replace('[yy]',(''+dObj.getFullYear()).substr(2));else if(frm.indexOf('[yyyy]')!=-1)
frm=frm.replace('[yyyy]',''+dObj.getFullYear());if(frm.indexOf('[wday]')!=-1)
frm=frm.replace('[wday]',$u.days[dObj.getDay()]);else if(frm.indexOf('[Wday]')!=-1)
frm=frm.replace('[Wday]',$u.s.changeCase($u.days[dObj.getDay()],'fu'));else if(frm.indexOf('[WDAY]')!=-1)
frm=frm.replace('[WDAY]',$u.days[dObj.getDay()].toUpperCase());else if(frm.indexOf('[wd]')!=-1)
frm=frm.replace('[wd]',$u.daysShort[dObj.getDay()]);else if(frm.indexOf('[Wd]')!=-1)
frm=frm.replace('[Wd]',$u.s.changeCase($u.daysShort[dObj.getDay()],'fu'));else if(frm.indexOf('[WD]')!=-1)
frm=frm.replace('[WD]',$u.daysShort[dObj.getDay()].toUpperCase());var hr=dObj.getHours();var mer=hr>11?'pm':'am';if(hr==0)hr=24;if(frm.indexOf('[t:h]')!=-1){if(hr>12)hr=hr-12;frm=frm.replace('[t:h]',''+hr);}else if(frm.indexOf('[t:hh]')!=-1){if(hr>12)hr=hr-12;frm=frm.replace('[t:hh]',$u.s.pad(''+hr,2,'0'));}else if(frm.indexOf('[t:mh]')!=-1)
frm=frm.replace('[t:mh]',''+hr);else if(frm.indexOf('[t:mhh]')!=-1)
frm=frm.replace('[t:mhh]',$u.s.pad(''+hr,2,'0'));if(frm.indexOf('[t:m]')!=-1)
frm=frm.replace('[t:m]',''+(dObj.getMinutes()+1));else if(frm.indexOf('[t:mm]')!=-1)
frm=frm.replace('[t:mm]',$u.s.pad(''+(dObj.getMinutes()+1),2,'0'));if(frm.indexOf('[t:s]')!=-1)
frm=frm.replace('[t:s]',''+(dObj.getSeconds()+1));else if(frm.indexOf('[t:ss]')!=-1)
frm=frm.replace('[t:ss]',$u.s.pad(''+(dObj.getSeconds()+1),2,'0'));if(frm.indexOf('[t:am]')!=-1)
frm=frm.replace('[t:am]',mer);if(frm.indexOf('[t:a]')!=-1)
frm=frm.replace('[t:a]',mer.substr(0,1));else if(frm.indexOf('[t:AM]')!=-1)
frm=frm.replace('[t:AM]',mer.toUpperCase());else if(frm.indexOf('[t:A]')!=-1)
frm=frm.replace('[t:A]',mer.substr(0,1).toUpperCase());return frm;}},b:{toStr:function(valBool,rTrue,rFalse){return valBool?rTrue:rFalse;}}}
if(!$e){var $e={loaded:false,_e:[],_de:[],_dee:[],_ue:[],_ae:{},_aeg:{i:0,a:[],dhTO:0,sT:0,sX:0,sY:0,iX:[],iY:[],maxX:0,maxY:0,minX:0,minY:0,lClick:0},add:function(evntEle,evntType,evntFunc){var evntScope=arguments[3]?arguments[3]:null;var scopeOverride=typeof arguments[4]=='boolean'?arguments[4]:false;var groupName=arguments[5]?arguments[5]:'';if(evntEle&&evntEle.length&&!evntEle.tagName&&typeof evntEle!='string'&&!evntEle.alert&&typeof evntEle[0]!='undefined'){var returnBool=true;for(var i=0;i<evntEle.length;i++){returnBool=(($e.add(evntEle[i],evntType,evntFunc,evntScope,scopeOverride,groupName))&&returnBool)}
return returnBool;}
if($e.loaded){var ele=$(evntEle);if(!ele)return false;var cScope=(scopeOverride)?evntScope:ele;var wFunc=function(e){return evntFunc.call(cScope,$e.getEvent(e),evntScope);};if(evntType=='load'){wFunc();delete wFunc
delete ele;delete cScope;return true;}else if(evntType=='unload'){$e._ue.push([ele,evntType,evntFunc,wFunc,evntScope,scopeOverride,groupName]);return true;}else if(evntType.substr(0,8)=='abstract'&&!$e.abstractEvents.disabled){if(ele.id=='')ele.id=A5.u.getUniqueId();if(!$e._ae[ele.id]){$e._ae[ele.id]={ele:ele,dt:false,ut:false,mt:false,d:[],u:[],m:[],g:[]};}else if($e._ae[ele.id].ele!=ele){delete $e._ae[ele.id].ele;$e._ae[ele.id]={ele:ele,dt:false,ut:false,mt:false,d:[],u:[],m:[],g:[]};}
var subType=evntType.substr(8);var supportMouse=!(navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?true:false);var supportTouch=(navigator.userAgent.match(/android/i)||!!('createTouch'in document));if(subType=='down'){if($ga(ele,'A5AbstEvntD')!='true'){if(window.navigator.msPointerEnabled)$e.add(ele,'MSPointerDown',$e._aetDown);else{if(supportTouch)$e.add(ele,'touchstart',$e._aetDown);if(supportMouse)$e.add(ele,'mousedown',$e._aemDown);}
$sa(ele,'A5AbstEvntD','true');for(var i=$e._ae[ele.id].d.length-1;i>=0;i--){if($e._ae[ele.id].d[i]){delete $e._ae[ele.id].d[i][0];delete $e._ae[ele.id].d[i][1];delete $e._ae[ele.id].d[i];}}
$e._ae[ele.id].d=[];}
$e._ae[ele.id].d.push([evntFunc,wFunc,evntScope,scopeOverride,groupName]);}else if(subType=='up'){if($ga(ele,'A5AbstEvntU')!='true'){if(window.navigator.msPointerEnabled)$e.add(ele,'MSPointerUp',$e._aetUp);else{if(supportTouch)$e.add(ele,'touchend',$e._aetUp);if(supportMouse)$e.add(ele,'mouseup',$e._aemUp);}
$sa(ele,'A5AbstEvntU','true');for(var i=$e._ae[ele.id].u.length-1;i>=0;i--){if($e._ae[ele.id].u[i]){delete $e._ae[ele.id].u[i][0];delete $e._ae[ele.id].u[i][1];delete $e._ae[ele.id].u[i];}}
$e._ae[ele.id].u=[];}
$e._ae[ele.id].u.push([evntFunc,wFunc,evntScope,scopeOverride,groupName]);}else if(subType=='move'){if($ga(ele,'A5AbstEvntM')!='true'){if(window.navigator.msPointerEnabled)$e.add(ele,'MSPointerMove',$e._aetMove);else{if(supportTouch)$e.add(ele,'touchmove',$e._aetMove);if(supportMouse)$e.add(ele,'mousemove',$e._aemMove);}
$sa(ele,'A5AbstEvntM','true');for(var i=$e._ae[ele.id].m.length-1;i>=0;i--){if($e._ae[ele.id].m[i]){delete $e._ae[ele.id].m[i][0];delete $e._ae[ele.id].m[i][1];delete $e._ae[ele.id].m[i];}}
$e._ae[ele.id].m=[];}
$e._ae[ele.id].m.push([evntFunc,wFunc,evntScope,scopeOverride,groupName]);}else{if($ga(ele,'A5AbstEvntG')!='true'){$e.add(ele,'abstractdown',$e._aegStart);$sa(ele,'A5AbstEvntG','true');for(var i=$e._ae[ele.id].g.length-1;i>=0;i--){if($e._ae[ele.id].g[i]){delete $e._ae[ele.id].g[i][0];delete $e._ae[ele.id].g[i][1];delete $e._ae[ele.id].g[i];}}
$e._ae[ele.id].g=[];if($ga(document.documentElement,'A5AbstEvntG')!='true'){$e.add(document.documentElement,'abstractmove',$e._aegMove);$e.add(document.documentElement,'abstractup',$e._aegEnd);$sa(document.documentElement,'A5AbstEvntG','true');}}
$e._ae[ele.id].g.push([evntType,evntFunc,wFunc,evntScope,scopeOverride,groupName]);$e._aeg.i++;}
return true;}
if($e.abstractEvents.disabled){if(evntType.substr(0,8)=='abstract'){if(evntType=='abstractdown')evntType='mousedown';else if(evntType=='abstractup')evntType='mouseup';else if(evntType=='abstractmove')evntType='mousemove';else if(evntType=='abstractclick')evntType='click';else if(evntType=='abstractdblclick')evntType='dblclick';}}
$e._e.push([ele,evntType,evntFunc,wFunc,evntScope,scopeOverride,groupName]);if(ele.addEventListener)ele.addEventListener(evntType,wFunc,false);else if(ele.attachEvent)ele.attachEvent('on'+evntType,wFunc);}else{$e._de.push([evntEle,evntType,evntFunc,evntScope,scopeOverride,groupName]);}
return true;},remove:function(ele,evntType,evntFunc){if(evntType.substr(0,8)=='abstract'){if($e._ae[ele.id]){var subType=evntType.substr(8);if(subType=='down'){var evnts=$e._ae[ele.id].d;for(var i=evnts.length-1;i>=0;i--){if(evnts[i]){if(evnts[i][0]==evntFunc){delete evnts[i][0];delete evnts[i][1];delete evnts[i];evnts.splice(i,1);}}}
if($ga(ele,'A5AbstEvntD')=='true'&&evnts.length==0){if(window.navigator.msPointerEnabled)$e.remove(ele,'MSPointerDown',$e._aetDown);else{$e.remove(ele,'touchstart',$e._aetDown);$e.remove(ele,'mousedown',$e._aemDown);}
$sa(ele,'A5AbstEvntD','');}}else if(subType=='up'){var evnts=$e._ae[ele.id].u;for(var i=evnts.length-1;i>=0;i--){if(evnts[i]){if(evnts[i][0]==evntFunc){delete evnts[i][0];delete evnts[i][1];delete evnts[i];evnts.splice(i,1);}}}
if($ga(ele,'A5AbstEvntU')=='true'&&evnts.length==0){if(window.navigator.msPointerEnabled)$e.remove(ele,'MSPointerUp',$e._aetUp);else{$e.remove(ele,'touchend',$e._aetUp);$e.remove(ele,'mouseup',$e._aemUp);}
$sa(ele,'A5AbstEvntU','');}}else if(subType=='move'){var evnts=$e._ae[ele.id].m;for(var i=evnts.length-1;i>=0;i--){if(evnts[i]){if(evnts[i][0]==evntFunc){delete evnts[i][0];delete evnts[i][1];delete evnts[i];evnts.splice(i,1);}}}
if($ga(ele,'A5AbstEvntM')=='true'&&evnts.length==0){if(window.navigator.msPointerEnabled)$e.remove(ele,'MSPointerMove',$e._aetMove);else{$e.remove(ele,'touchmove',$e._aetMove);$e.remove(ele,'mousemove',$e._aemMove);}
$sa(ele,'A5AbstEvntM','');}}else{var evnts=$e._ae[ele.id].g;for(var i=evnts.length-1;i>=0;i--){if(evnts[i]){if(evnts[i][0]==evntFunc){delete evnts[i][1];delete evnts[i][2];delete evnts[i];evnts.splice(i,1);$e._aeg.i--;}}}
if($ga(ele,'A5AbstEvntG')=='true'&&evnts.length==0){$e.remove(ele,'abstractdown',$e._aegStart);$sa(ele,'A5AbstEvntG','');}}
return true;}}
if(typeof ele=='string'){ele=$(ele);}else if(ele&&typeof ele.length!='undefined'&&!ele.tagName&&typeof ele!='string'&&!ele.alert&&typeof ele[0]!='undefined'){var returnBool=true;for(var i=0;i<ele.length;i++){returnBool=($e.remove(ele[i],evntType,evntFunc)&&returnBool)}
return returnBool;}
var eObj=null;var eIndx=arguments[3]?arguments[3]:$e._wf(ele,evntType,evntFunc);if(eIndx==-1){for(var i=0;i<$e._ue.length;i++){if($e._ue[i]){if($e._ue[i][0]==ele&&$e._ue[i][1]==evntType&&$e._ue[i][2]==evntFunc){delete $e._ue[i][2];delete $e._ue[i];return true;}}}
return false;}
eObj=$e._e[eIndx];if(ele.removeEventListener)ele.removeEventListener(evntType,eObj[3],false);else if(ele.detachEvent)ele.detachEvent('on'+evntType,eObj[3]);delete $e._e[eIndx][3];delete $e._e[eIndx][2];delete $e._e[eIndx];return true;},removeGroup:function(gName){for(var i=0;i<$e._e.length;i++){var eObj=$e._e[i];if(eObj){if(eObj[6]==gName){if(eObj[0])$e.remove(eObj[0],eObj[1],eObj[2],i);else{delete eObj[0];delete eObj[3];delete eObj[2];delete $e._e[i];}}}}
var evnts=0;var hadRemEvnts=false;for(var eleId in $e._ae){evnts=$e._ae[eleId].d;for(var i=evnts.length-1;i>=0;i--){if(evnts[i][5]==gName){delete evnts[i][0];delete evnts[i][1];delete evnts[i];evnts.splice(i,1);hadRemEvnts=true;}}
if(evnts.length==0&&hadRemEvnts){var ele=$(eleId);$e.remove(ele,'touchstart',$e._aetDown);$e.remove(ele,'mousedown',$e._aemDown);$sa(ele,'A5AbstEvntd','');}
hadRemEvnts=false;evnts=$e._ae[eleId].u;for(var i=evnts.length-1;i>=0;i--){if(evnts[i][5]==gName){delete evnts[i][0];delete evnts[i][1];delete evnts[i];evnts.splice(i,1);hadRemEvnts=true;}}
if(evnts.length==0&&hadRemEvnts){var ele=$(eleId);$e.remove(ele,'touchend',$e._aetUp);$e.remove(ele,'mouseup',$e._aemUp);$sa(ele,'A5AbstEvntU','');}
hadRemEvnts=false;evnts=$e._ae[eleId].m;for(var i=evnts.length-1;i>=0;i--){if(evnts[i][5]==gName){delete evnts[i][0];delete evnts[i][1];delete evnts[i];evnts.splice(i,1);hadRemEvnts=true;}}
if(evnts.length==0&&hadRemEvnts){var ele=$(eleId);$e.remove(ele,'touchmove',$e._aetMove);$e.remove(ele,'mousemove',$e._aemMove);$sa(ele,'A5AbstEvntM','');}
hadRemEvnts=false;evnts=$e._ae[eleId].g;for(var i=evnts.length-1;i>=0;i--){if(evnts[i][5]==gName){delete evnts[i][0];delete evnts[i][1];delete evnts[i];evnts.splice(i,1);hadRemEvnts=true;}}
if(evnts.length==0&&hadRemEvnts){var ele=$(eleId);$e.remove(ele,'abstractdown',$e._aegStart);$sa(ele,'A5AbstEvntG','');}}
for(var i=0;i<$e._ue.length;i++){if($e._ue[i]){if($e._ue[i][6]==gName){delete $e._ue[i][0];delete $e._ue[i][3];delete $e._ue[i][2];delete $e._ue[i];}}}},execute:function(ele,evntType){if(!$e.loaded){$e._dee.push([ele,evntType]);return false;}
var ele=$(ele);if(!ele)return false;var e={};if(evntType.substr(0,8)=='abstract'){if($e._ae[ele.id]){var subType=evntType.substr(8);if(subType=='down'){var evnts=$e._ae[ele.id].d;for(var i=0;i<evnts.length;i++)evnts[i][1](e);}else if(subType=='up'){var evnts=$e._ae[ele.id].u;for(var i=0;i<evnts.length;i++)evnts[i][1](e);}else if(subType=='move'){var evnts=$e._ae[ele.id].m;for(var i=0;i<evnts.length;i++)evnts[i][1](e);}else{var evnts=$e._ae[ele.id].g;for(var i=0;i<evnts.length;i++){if(evnts[i][0]==evntType)evnts[i][2](e);}}}
return;}
if(ele['on'+evntType])ele['on'+evntType]();for(var i=0;i<$e._e.length;i++){if($e._e[i]){if($e._e[i][0]==ele&&$e._e[i][1]==evntType){$e._e[i][3](e);}}}},executeGroup:function(gName){for(var i=0;i<$e._e.length;i++){var eObj=$e._e[i];if(eObj){if(eObj[6]==gName)eObj[3]();}}},getEvent:function(e){var evnt=e||window.event;return evnt},getCharCode:function(e){e=$e.getEvent(e);return e.charCode||e.keyCode;},getTouches:function(e){if(e.originalEvent){if(e.originalEvent.touches&&e.originalEvent.touches.length)return e.originalEvent.touches;else if(e.originalEvent.changedTouches&&e.originalEvent.changedTouches.length)return e.originalEvent.changedTouches;}else{if(e.touches||e.changedTouches){if(e.touches.length)return e.touches;else if(e.changedTouches.length)return e.changedTouches;}}
return null;},getCoors:function(e){var coors={};var tempT=$e.getTouches(e);if(tempT){if(tempT.length){coors.clientX=tempT[0].clientX;coors.clientY=tempT[0].clientY;return coors;}}
coors.clientX=e.clientX;coors.clientY=e.clientY;return coors;},stopEvent:function(e){e=$e.getEvent(e);$e.stopPropagation(e);$e.preventDefault(e);},stopPropagation:function(e){e=$e.getEvent(e);if(e.stopPropagation)e.stopPropagation();else e.cancelBubble=true;},preventDefault:function(e){e=$e.getEvent(e);if(e.preventDefault)e.preventDefault();else e.returnValue=false;},_wf:function(eEle,eType,eFn){for(var i=0;i<$e._e.length;i++){if($e._e[i])
if($e._e[i][0]==eEle&&$e._e[i][1]==eType&&$e._e[i][2]==eFn)return i;}
return-1},_pageLoad:function(){if(!$e.loaded){$e.loaded=true;for(var i=0;i<$e._de.length;i++)$e.add.call($e,$e._de[i][0],$e._de[i][1],$e._de[i][2],$e._de[i][3],$e._de[i][4],$e._de[i][5]);for(var i=0;i<$e._dee.length;i++)$e.execute.apply($e,$e._dee[i]);if($e.onLoaded.constructor==Function)$e.onLoaded();}},_pageUnload:function(e){for(var i=0;i<$e._ue.length;i++){if($e._ue[i]){$e._ue[i][3](e);delete $e._ue[i][0];delete $e._ue[i][3];delete $e._ue[i][2];delete $e._ue[i];}}
for(var i=0;i<$e._e.length;i++){if($e._e[i]){if($e._e[i][0])$e.remove($e._e[i][0],$e._e[i][1],$e._e[i][2],i);}}},_aetDown:function(e){$e._ae[this.id].dt=new Date().getTime();$e._aeDown(this,e);},_aemDown:function(e){if($e._ae[this.id]){if($e._ae[this.id].dt){if(new Date().getTime()-$e._ae[this.id].dt<1000){$e._ae[this.id].dt=false;return;}}}
$e._aeDown(this,e);},_aeDown:function(ele,e){if(ele.disabled==true)return false;var evnts=$e._ae[ele.id].d;for(var i=0;i<evnts.length;i++)evnts[i][1](e);},_aetUp:function(e){$e._ae[this.id].ut=new Date().getTime();$e._aeUp(this,e);},_aemUp:function(e){if($e._ae[this.id]){if($e._ae[this.id].ut){if(new Date().getTime()-$e._ae[this.id].ut<1000){$e._ae[this.id].ut=false;return;}}}
$e._aeUp(this,e);},_aeUp:function(ele,e){var evnts=$e._ae[ele.id].u;for(var i=0;i<evnts.length;i++)evnts[i][1](e);},_aetMove:function(e){$e._ae[this.id].mt=new Date().getTime();$e._aeMove(this,e);},_aemMove:function(e){if($e._ae[this.id]){if($e._ae[this.id].mt){if(new Date().getTime()-$e._ae[this.id].mt<1000){$e._ae[this.id].mt=false;return;}}}
$e._aeMove(this,e);},_aeMove:function(ele,e){var evnts=$e._ae[ele.id].m;for(var i=0;i<evnts.length;i++)evnts[i][1](e);},_aegStart:function(e){if(!e.type)return;$e._aeg.a.push(this.id);if($e._aeg.a.length==1){var coor=$e.getCoors(e);$e._aeg.sT=new Date().getTime();$e._aeg.x=coor.clientX;$e._aeg.y=coor.clientY;$e._aeg.sX=coor.clientX;$e._aeg.sY=coor.clientY;$e._aeg.maxX=coor.clientX;$e._aeg.maxY=coor.clientY;$e._aeg.minX=coor.clientX;$e._aeg.minY=coor.clientY;$e._aeg.dh=false;$e._aeg.dhTO=setTimeout($e._aegHold,$e.abstractEvents.downHold.duration);}},_aegMove:function(e){if(!$e._aeg.a)return;var coor=$e.getCoors(e);$e._aeg.x=coor.clientX;$e._aeg.y=coor.clientY;$e._aeg.maxX=Math.max($e._aeg.maxX,coor.clientX);$e._aeg.maxY=Math.max($e._aeg.maxY,coor.clientY);$e._aeg.minX=Math.min($e._aeg.minX,coor.clientX);$e._aeg.minY=Math.min($e._aeg.minY,coor.clientY);},_aegEnd:function(e){if($e._aeg.a.length==0)return true;if(document.all&&navigator.appName!='Opera'){$e._aegEvntObj={};for(var p in e)$e._aegEvntObj[p]=e[p];$e._aegEvntObj.preventDefault=false;$e._aegEvntObj.stopPropagation=false;}else $e._aegEvntObj=e;setTimeout($e._aegEndCom,0);},_aegEndCom:function(){var e=$e._aegEvntObj;var coor=$e.getCoors(e);clearTimeout($e._aeg.dhTO);var tn=new Date().getTime();var isTap=false;var isDblTap=false;var isSwipe=false;var dX=Math.max($e._aeg.sX-$e._aeg.minX,$e._aeg.maxX-$e._aeg.sX);var dY=Math.max($e._aeg.sY-$e._aeg.minY,$e._aeg.maxY-$e._aeg.sY);var dist=Math.sqrt((dX*dX)+(dY*dY));if(dist<=$e.abstractEvents.tap.wiggle){isTap=true;if((tn-$e._aeg.lTap)<=$e.abstractEvents.dblTap.duration)isDblTap=true;$e._aeg.lTap=tn;}
if(dist/(tn-$e._aeg.sT)>=$e.abstractEvents.swipe.velocity){isSwipe=true;var hDir='left';var vDir='up';if($e._aeg.sX-$e._aeg.minX<$e._aeg.maxX-$e._aeg.sX)hDir='right';if($e._aeg.sY-$e._aeg.minY<$e._aeg.maxY-$e._aeg.sY)vDir='down';if(dX>=dY){e.swipeDirection=hDir;}else{e.swipeDirection=vDir;}}
e.abstractData={x:$e._aeg.x,y:$e._aeg.y,startX:$e._aeg.sX,startY:$e._aeg.sY,endX:coor.clientX,endY:coor.clientY,maxX:$e._aeg.maxX,maxY:$e._aeg.maxY,minX:$e._aeg.minX,minY:$e._aeg.minY,downHold:$e._aeg.dh};var tA=$u.a.dedup($e._aeg.a.join('\n').split('\n'));$e._aeg.a=[];$e._aeg.sT=0;$e._aeg.sX=0;$e._aeg.sY=0;$e._aeg.maxX=5000;$e._aeg.maxY=5000;$e._aeg.minX=-5000;$e._aeg.minY=-5000;var tResult=true;var pClick=$if(A5.u.drag._sDif<$e.abstractEvents.click.scrollMax,true,false);var pDblClick=pClick;var canBeDblClick=(tn-$e._aeg.lClick)<=$e.abstractEvents.dblClick.duration;for(var j=0;j<tA.length;j++){if($e._ae[tA[j]]){var evnts=$e._ae[tA[j]].g;for(var i=0;i<evnts.length;i++){var subType=evnts[i][0].substr(8);var disabled=$e._ae[tA[j]].ele.disabled;if((subType=='click'||subType=='dblclick')&&disabled!=true&&pClick){var b=$e._ae[tA[j]].ele.getBoundingClientRect();if(coor.clientY>=b.top&&coor.clientY<=b.top+b.height&&coor.clientX>=b.left&&coor.clientX<=b.left+b.width){$e._aeg.lClick=tn;if(subType=='click'){tResult=evnts[i][2](e);if(typeof tResult=='boolean'&&tResult==false)pClick=false;}
if(subType=='dblclick'&&canBeDblClick&&pDblClick){tResult=evnts[i][2](e);if(typeof tResult=='boolean'&&tResult==false)pDblClick=false;}}}else if(subType=='tap'){if(isTap){tResult=evnts[i][2](e);if(typeof tResult=='boolean'&&tResult==false)isTap=false;}}else if(subType=='dbltap'){if(isDblTap){tResult=evnts[i][2](e);if(typeof tResult=='boolean'&&tResult==false)isDblTap=false;}}else if(subType=='swipe'){if(isSwipe){tResult=evnts[i][2](e);if(typeof tResult=='boolean'&&tResult==false)isSwipe=false;}}}}}},_aegHold:function(){var dX=Math.max($e._aeg.sX-$e._aeg.minX,$e._aeg.maxX-$e._aeg.sX);var dY=Math.max($e._aeg.sY-$e._aeg.minY,$e._aeg.maxY-$e._aeg.sY);var dist=Math.sqrt((dX*dX)+(dY*dY));if(dist<=$e.abstractEvents.downHold.wiggle){var e={type:'abstractdownhold',clientX:$e._aeg.x,clientY:$e._aeg.y,abstractData:{x:$e._aeg.x,y:$e._aeg.y,startX:$e._aeg.sX,startY:$e._aeg.sY,maxX:$e._aeg.maxX,maxY:$e._aeg.maxY,minX:$e._aeg.minX,minY:$e._aeg.minY}};$e._aeg.dh=true;for(var j=0;j<$e._aeg.a.length;j++){if($e._ae[$e._aeg.a[j]]){if($e._ae[$e._aeg.a[j]].g){var evnts=$e._ae[$e._aeg.a[j]].g;for(var i=0;i<evnts.length;i++){if(evnts[i][0].substr(8)=='downhold')evnts[i][2](e);}}}}}},onLoaded:0,abstractEvents:{disabled:false,tap:{wiggle:10},dblTap:{duration:600},click:{scrollMax:20},dblClick:{duration:600},downHold:{duration:600,wiggle:10},swipe:{velocity:.75}}}
$ae(window,'load',$e._pageLoad);$ae(window,'unload',$e._pageUnload);}
var $a=new Object();$a.simple=Class.create();$a.simple.prototype={initialize:function(url,options){this.transport=this.getTransport();this.method=options.method||'post';this.async=options.async||true;this.handleGeneric=options.handleGeneric||false;this.handleType=options.handleType||'eval';this.handleContext=options.handleContext||false;this.onprogress=options.onprogress||false;this.onload=options.onload||false;this.onerror=options.onerror||false;this.onabort=options.onabort||false;this.timeout=options.timeout||false;if(this.handleGeneric==true){if(this.handleType=='eval'){this.handle=$a._rh._eval;}}else{this.handle=options.handle||null;}
this.errorHandle=options.errorHandle||$a._rh._error;this.errorHandleContext=options.errorHandleContext||null;this.data=options.data||'';if(typeof A5!='undefined'){if(typeof A5.ajax!='undefined'){if(typeof A5.ajax.addParamRequiredData!='undefined')this.data=A5.ajax.addParamRequiredData(this.data);}}
var data=this.data.split('&');var dataI=0;var prop='';var obj={};for(var i=0;i<data.length;i++){dataI=data[i].split('=');prop=dataI.shift();dataI=dataI.join('=');if(prop.substr(prop.length-2)=='[]'){prop=prop.substr(0,prop.length-2);if(typeof obj[prop]=='undefined')obj[prop]=[];obj[prop].push(dataI);}else obj[prop]=dataI;}
this.data=$u.o.toParams(obj,'',false);this.fill=$(options.fill)||null;this.url=url;this._secondChance=true;$a.lastCallback=new Date().getTime();this.initCallback=$a.lastCallback;this.request();},request:function(){this.transport.open(this.method,this.url,this.async);if(this.timeout)this.transport.timeout=this.timeout;var func=this.onChange;var context=this;this.transport.onreadystatechange=function(){return func.call(context);};if(this.method=='post'){this.transport.setRequestHeader('Content-type','application/x-www-form-urlencoded; charset=UTF-8');if(this.transport.overrideMimeType){try{this.transport.overrideMimeType('text/html; charset=UTF-8');}catch(e){console.log('Error -> '+e);}}}
if(this.onprogress){this.transport.onprogress=this.onprogress;this.transport.upload.onprogress=this.onprogress;}
if(this.onload){this.transport.onload=this.onload;this.transport.upload.onload=this.onload;}
if(this.onerror){this.transport.onerror=this.onerror;this.transport.upload.onerror=this.onerror;}
if(this.onabort){this.transport.onabort=this.onabort;this.transport.upload.onabort=this.onabort;}
this.transport.setRequestHeader('X-Requested-With','XMLHttpRequest');this.transport.send(this.data);},onChange:function(){if(this.transport.readyState==4&&this.transport.status==200){var func=this.handle;var funcContext=this.handleContext||func;var context=this;if(func)setTimeout(function(){return func.call(funcContext,context.transport);},10);if($a._def[''+this.initCallback])setTimeout(Function('$a._def[\''+this.initCallback+'\'](); delete $a._def[\''+this.initCallback+'\'];'),20);var obj=this.fill;if(obj)setTimeout(function(){return $svs(obj,context.transport.responseText);},10);}else if(this.transport.readyState==4&&this.transport.status==408&&this._secondChance){$a.lastCallback=new Date().getTime();this.request();this._secondChance=false;}else if(this.transport.readyState==4&&this.transport.status!=200){var func=this.errorHandle;var funcContext=this.errorHandleContext||func;var context=this;if(func)setTimeout(function(){return func.call(funcContext,context.transport);},10);var obj=this.fill;if(obj)setTimeout(function(){return $svs(obj,context.transport.responseText);},10);}},getTransport:function(){trans=false;try{trans=new XMLHttpRequest();}catch(err){if(window.ActiveXObject)trans=new ActiveXObject('Microsoft.XMLHTTP');}
return trans;}}
$a._def={};$a.lastCallback=new Date().getTime();$a._rh={_eval:function(obj){if(obj.responseText)eval(obj.responseText);},_error:function(obj){var pText=obj.responseText;if(pText.search('</body>')!=-1)pText=$u.s.word($u.s.word(pText,2,'<body>'),1,'</body>');var pText=$u.s.aTrim(pText.replace(/(<([^>]+)>)/ig,''),'\n\r  ');if(pText!='')alert('XHTTPRequest Error:\n\n'+pText);}}